### ISSUE TITLE
cluster_copy(): Error in env_get_list(env, names, inherit = TRUE) : argument "default" is missing, with no default

### ISSUE THREAD

**Issue by ksallinger1** [tidyverse/multidplyr#121]
cluster_copy() returns the following rlang error: 

```r
cluster <- new_cluster(14)
envList <- c("temp", "fctA", "fctB")
cluster_copy(cluster, envList)

Error in env_get_list(env, names, inherit = TRUE) : 
  argument "default" is missing, with no default
```
I recently updated R & packages to the latest versions, prior to that everything worked fine.
R version 4.1.0 (2021-05-18)
Windows 10, x86_64-w64-mingw32
multidplyr version 0.1.0
rlang version 0.4.11

**Comment by jaclynbeca** [comment]
I'm getting the same error

**Comment by Fredo-XVII** [comment]
I am also getting the same error.  I am trying to copy a function over to the cluster and it is erroring out.  Could we get an update or a fix for this issue.  This is currently breaking that I had built with R3.63, and it is breaking in R 4.0.2.  I don't have a regex because it is work related code.  I do apologize about that because I know that I am not being helpful.

```
Error in env_get_list(env, names, inherit = TRUE) :
  argument "default" is missing, with no default
  
```
